backend:
  # name: test-repo
  # name: git-gateway
  # branch: master
  name: github
  repo: ewgdg/my-page
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "blogPost"
    label: "Blog Post"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "BlogPost"}
      - {label: "Title", name: "title", widget: "string", default: 'untitled'}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Featured Post", name: "featuredPost", widget: "boolean", default: false }
      - {label: "Featured Image", name: "featuredimage", widget: image, required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}
      - {label: "Tags", name: "tags", widget: "list", requiored: false}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "indexPage"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "IndexPage"}
          - {label: Title, name: title, widget: string} 
          - {label: Jumbotron, name: jumbotron, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Headline, name: headline, widget: text}, {label: Subtitle, name: subtitle, widget: string}]}
        
      - file: "src/pages/blog/index.md"
        label: "Blog List Page"
        name: "blogListPage"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "BlogPage"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: Jumbotron, name: jumbotron, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Headline, name: headline, widget: text}, {label: Subtitle, name: subtitle, widget: string}]}
       - file: "src/pages/about.md"
        label: "About Page"
        name: "aboutPage"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "AboutPage"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: Jumbotron, name: jumbotron, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Headline, name: headline, widget: text}, {label: Subtitle, name: subtitle, widget: string}]}
      