backend:
  name: git-gateway
  branch: master

local_backend: true

media_folder: public/img
public_folder: /img

collections:
  - name: "blogPost"
    label: "Blog Post"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "BlogPost"}
      - {label: "Title", name: "title", widget: "string", default: 'untitled'}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Featured Post", name: "featuredPost", widget: "boolean", default: false }
      - {label: "Featured Image", name: "featuredImage", widget: image, required: false}
      - {label: "Is Portfolio", name: "isPortfolio", widget: "hidden", default: false}
      - {label: "External Link", name: "externalLink", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}
      - {label: "Tags", name: "tags", widget: "list", required: false}
  - name: "portfolioPost"
    label: "Portfolio Post"
    folder: "content/portfolio"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string", default: 'untitled'}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Featured Post", name: "featuredPost", widget: "boolean", default: false }
      - {label: "Featured Image", name: "featuredImage", widget: image, required: false}
      - {label: "External Link", name: "externalLink", widget: "string", required: false}
      - {label: "Is Portfolio", name: "isPortfolio", widget: "hidden", default: true}
      - {label: "Body", name: "body", widget: "markdown", required: false}
      - {label: "Tags", name: "tags", widget: "list", required: false}

  - name: "pages"
    label: "Pages"
    files:
      - file: "content/index.md"
        label: "Landing Page"
        name: "indexPage"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "IndexPage"}
          - {label: Title, name: title, widget: string} 
          - {label: Jumbotron, name: jumbotron, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Headline, name: headline, widget: text}, {label: Subtitle, name: subtitle, widget: string}]}
        
      - file: "content/blog.md"
        label: "Blog List Page"
        name: "blogListPage"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "BlogPage"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: Jumbotron, name: jumbotron, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Headline, name: headline, widget: text}, {label: Subtitle, name: subtitle, widget: string}]}
      - file: "content/about.md"
        label: "About Page"
        name: "aboutPage"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "AboutPage"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: Jumbotron, name: jumbotron, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Headline, name: headline, widget: text}, {label: Subtitle, name: subtitle, widget: string}]}
