[project]
name = "qa-chatbot"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "openai",
    "requests",
    "cachecontrol",
    "cachetools",
    "pydantic",
]